from enum import Enum
from enum import IntEnum

#
# MIT License
#
# https://opensource.org/licenses/MIT
#
# Copyright 2020 Rene Sugar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Description:
#
# This file contains constants.
#

NOTES_FOLDER_NAME = "Notes"
NOTES_FOLDER_UUID = "2e7ca3c0de554a7b870630ea2848e731"
NOTES_UNTITLED    = "Untitled"

#
# Joplin note type
#
class JoplinType(IntEnum):
  JOPLIN_TYPE_NOTE = 1
  JOPLIN_TYPE_FOLDER = 2
  JOPLIN_TYPE_SETTING = 3
  JOPLIN_TYPE_RESOURCE = 4
  JOPLIN_TYPE_TAG = 5
  JOPLIN_TYPE_NOTE_TAG = 6
  JOPLIN_TYPE_SEARCH = 7
  JOPLIN_TYPE_ALARM = 8
  JOPLIN_TYPE_MASTER_KEY = 9
  JOPLIN_TYPE_ITEM_CHANGE = 10
  JOPLIN_TYPE_NOTE_RESOURCE = 11
  JOPLIN_TYPE_RESOURCE_LOCAL_STATE = 12
  JOPLIN_TYPE_REVISION = 13
  JOPLIN_TYPE_MIGRATION = 14
  JOPLIN_TYPE_SMART_FILTER = 15

#
# Notes table column indices
#
class NotesColumns(IntEnum):
  NOTE_ID = 0
  NOTE_TYPE = 1
  NOTE_UUID = 2
  NOTE_PARENT_UUID = 3
  NOTE_TAG_UUID = 4
  NOTE_NOTE_UUID = 5
  NOTE_ORIGINAL_FORMAT = 6
  NOTE_INTERNAL_DATE = 7
  NOTE_HASH = 8
  NOTE_TITLE = 9
  NOTE_DATA = 10
  NOTE_DATA_FORMAT = 11
  NOTE_URL = 12
  EMAIL_FILENAME = 13
  EMAIL_FROM = 14
  EMAIL_X_UNIFORM_TYPE_IDENTIFIER = 15
  EMAIL_CONTENT_TYPE = 16
  EMAIL_CONTENT_TRANSFER_ENCODING = 16
  EMAIL_MIME_VERSION = 18
  EMAIL_DATE = 19
  EMAIL_X_MAIL_CREATED_DATE = 20
  EMAIL_SUBJECT = 21
  EMAIL_X_UNIVERSALLY_UNIQUE_IDENTIFIER = 22
  EMAIL_MESSAGE_ID = 23
  EMAIL_BODY = 24
  APPLE_ID = 25
  APPLE_TITLE = 26
  APPLE_SNIPPET = 27
  APPLE_FOLDER = 28
  APPLE_CREATED = 29
  APPLE_LAST_MODIFIED = 30
  APPLE_DATA = 31
  APPLE_ATTACHMENT_ID = 32
  APPLE_ATTACHMENT_PATH = 33
  APPLE_ACCOUNT_DESCRIPTION = 34
  APPLE_ACCOUNT_IDENTIFIER = 35
  APPLE_ACCOUNT_USERNAME = 36
  APPLE_VERSION = 37
  APPLE_USER = 38
  APPLE_SOURCE = 39
  JOPLIN_ID = 40
  JOPLIN_PARENT_ID = 41
  JOPLIN_TYPE_ = 42
  JOPLIN_CREATED_TIME = 43
  JOPLIN_UPDATED_TIME = 44
  JOPLIN_IS_CONFLICT = 45
  JOPLIN_LATITUDE = 46
  JOPLIN_LONGITUDE = 47
  JOPLIN_ALTITUDE = 48
  JOPLIN_AUTHOR = 49
  JOPLIN_SOURCE_URL = 50
  JOPLIN_IS_TODO = 51
  JOPLIN_TODO_DUE = 52
  JOPLIN_TODO_COMPLETED = 53
  JOPLIN_SOURCE = 54
  JOPLIN_SOURCE_APPLICATION = 55
  JOPLIN_APPLICATION_DATA = 56
  JOPLIN_ORDER = 57
  JOPLIN_USER_CREATED_TIME = 58
  JOPLIN_USER_UPDATED_TIME = 59
  JOPLIN_ENCRYPTION_CIPHER_TEXT = 60
  JOPLIN_ENCRYPTION_APPLIED = 61
  JOPLIN_ENCRYPTION_BLOB_ENCRYPTED = 62
  JOPLIN_SIZE = 63
  JOPLIN_MARKUP_LANGUAGE = 64
  JOPLIN_IS_SHARED = 65
  JOPLIN_NOTE_ID = 66
  JOPLIN_TAG_ID = 67
  JOPLIN_MIME = 68
  JOPLIN_FILENAME = 69